/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dishwasher.glb -T -o ../../cocktail-thela-spa/src/thela/Dish.jsx 
Files: Dishwasher.glb [7.63MB] > /home/rnd/code/3D/thela/cocktail-thela-spa/src/thela/Dishwasher-transformed.glb [313.18KB] (96%)
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
    const { nodes, materials } = useGLTF('/Dishwasher.glb');
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.PaletteMaterial001} />
        </group>
    );
}

useGLTF.preload('/Dishwasher.glb');
