/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Rocks Glasses.glb -T -o Rock.jsx 
Files: Rocks Glasses.glb [25.04MB] > /home/rnd/code/3D/thela/GLB/orig/Rocks Glasses-transformed.glb [1.35MB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
      <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
      <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
    </group>
  )
}

useGLTF.preload('/Rock.glb')
