/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Roof.glb -o second_transform_jsx/Roof.jsx 
*/

import { useGLTF, useTexture } from '@react-three/drei';

export function Model({theme, ...props}) {
    const { scene, nodes } = useGLTF('/Roof.glb');

    let tex1, tex2, color;
    if (theme == 'apothecary' || theme == 'summer') {
        [tex1, tex2] = useTexture(['/roof_apo/baseColor_1.jpg', '/roof_apo/baseColor_2.jpg']);
        tex1.flipY = false;
        tex2.flipY = false;
        color = theme == 'apothecary' ? '#FFFFFF' : '#ababab';
    } else {
        [tex1, tex2] = [null, null];
        color = '#000000';
    }

    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Mesh_0.geometry} material={nodes.Mesh_0.material} />
            <mesh geometry={nodes.Mesh_1.geometry}>
                <meshStandardMaterial map={tex1} color={color}/>
            </mesh>
            <mesh geometry={nodes.Mesh_2.geometry}>
                <meshStandardMaterial map={tex2} color={color}/>
            </mesh>
            <mesh geometry={nodes.Mesh_3.geometry} material={nodes.Mesh_3.material} />
            <mesh geometry={nodes.Mesh_4.geometry} material={nodes.Mesh_4.material} />
            <mesh geometry={nodes.Mesh_5.geometry} material={nodes.Mesh_5.material} />
            <mesh geometry={nodes.Mesh_6.geometry} material={nodes.Mesh_6.material} />
        </group>
    );
}

useGLTF.preload('/Roof.glb');
