/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Wine Glasses.glb -T -o Wine.jsx 
Files: Wine Glasses.glb [1.44MB] > /home/rnd/code/3D/thela/GLB/orig/Wine Glasses-transformed.glb [105.29KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Wine.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/Wine.glb')
