/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Ice Machine.glb -T -o Ice.jsx 
Files: Ice Machine.glb [3.62MB] > /home/rnd/code/3D/thela/GLB/orig/Ice Machine-transformed.glb [146.13KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Ice.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/Ice.glb')
